// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webshopAPI.Models;

[Table("ItemCategory")]
public partial class ItemCategory
{
    [Key]
    public int IDItemCategory { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    [InverseProperty("ItemCategory")]
    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}