// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webshopAPI.Models;

[Table("OrderItem")]
public partial class OrderItem
{
    [Key]
    public int IDOrderItem { get; set; }

    public int OrderID { get; set; }

    public int ItemID { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("ItemID")]
    [InverseProperty("OrderItems")]
    public virtual Item Item { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("OrderItems")]
    public virtual Order Order { get; set; }
}