// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webshopAPI.Models;

[Table("Tag")]
[Index("Name", Name = "UQ_Tag_Name", IsUnique = true)]
public partial class Tag
{
    [Key]
    public int IDTag { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("Tag")]
    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}