// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webshopAPI.Models;

[Table("CartItem")]
public partial class CartItem
{
    [Key]
    public int IDCartItem { get; set; }

    public int CartID { get; set; }

    public int ItemID { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("CartID")]
    [InverseProperty("CartItems")]
    public virtual Cart Cart { get; set; }

    [ForeignKey("ItemID")]
    [InverseProperty("CartItems")]
    public virtual Item Item { get; set; }
}