// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webshopAPI.Models;

[Table("Item")]
public partial class Item
{
    [Key]
    public int IDItem { get; set; }

    public int ItemCategoryID { get; set; }

    public int? TagID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Title { get; set; }

    [Required]
    [Unicode(false)]
    public string Description { get; set; }

    public int StockQuantity { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Weight { get; set; }

    [InverseProperty("Item")]
    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    [ForeignKey("ItemCategoryID")]
    [InverseProperty("Items")]
    public virtual ItemCategory ItemCategory { get; set; }

    [InverseProperty("Item")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [ForeignKey("TagID")]
    [InverseProperty("Items")]
    public virtual Tag Tag { get; set; }
}